feat: add `options.xremap.enable` to determine whether the service should actually run
xremap/nix-flake pull request #65
Opened 2024-04-01 19:30 UTC by redxtech

currently, if you import the module, the service gets automatically defined and enabled.

this is not in line with how most services are defined, usually they have a `services.<service>.enable` option that determines whether the service should be running.

i have added that option, to allow determining whether the service should run.

i would have preferred to use a `lib.mkEnableOption` rather than `lib.mkOption`, so that it can be more inline with how most services are defined, but i didn't want my PR to break existing configs when they update, so i set it to default to `true`, so the current behavior isn't changed.

if you don't mind changing the default behavior, i can update this PR to use `lib.mkEnableOption` instead.

2024-04-01 21:42 UTC, VTimofeenko commented
Thanks for the PR!

I agree, this option would make sense if, say, one wants to temporarily disable xremap without taking out whatever machinery imports the module. And it is in line with the rest of the modules.

With regards to the choice between `mkEnableOption` and `mkOption`(on by default) I think the `mkOption` makes more sense since it will lead to fewer surprises among existing users. That being said, this behavior will need to be explicitly documented (I'll take care of it).

As for the actual code -- I think this option belongs in `lib/default.nix` and it should also affect the home manager module(`homeManagerModules/default.nix`). I can make this change in a separate commit or you could add it to your branch -- your call

2024-04-02 00:24 UTC, redxtech commented
I've updated my PR moving it to the `lib/default.nix` folder, definitely makes sense to share it with home-manager as well! I'd forgotten about that initially.

2024-04-02 01:12 UTC, VTimofeenko requested changes
One minor format change needed

2024-04-02 01:12 UTC, VTimofeenko commented on modules/default.nix
> +in with lib; {
`nix fmt` reformats this line

2024-04-02 02:15 UTC, redxtech commented
Good catch, I didn't run the formatter, and my editor automatically made that change!

Should be good now.

2024-04-02 02:23 UTC, merged

2024-04-02 02:23 UTC, VTimofeenko commented
Thanks! I'll write up the doc